package clientews;


import clases.FechaHora;
import java.awt.Toolkit;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JuanJo
 */
public class Dialog_formularioCursoCIA extends java.awt.Dialog {
String datos[];
    /**
     * Creates new form Dialog_formularioAgente
     */
    
    public JFrame_Principal menu;
    
    public Dialog_formularioCursoCIA(JFrame_Principal parent, boolean modal) {
        super(parent, modal);
        initComponents();
        FechaHora fecha = new FechaHora();
        fecha.fecha(jLabel_fecha_mostrar);
        fecha.hora(jLabel_hora_mostrar);
        this.menu=parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_fecha = new javax.swing.JLabel();
        jLabel_hora = new javax.swing.JLabel();
        jLabel_hora_mostrar = new javax.swing.JLabel();
        jLabel_fecha_mostrar = new javax.swing.JLabel();
        jTextField_idFuncionario = new javax.swing.JTextField();
        jLabel_idFuncionario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_idTipo1 = new javax.swing.JLabel();
        jLabel_idInfractor1 = new javax.swing.JLabel();
        jTextField_idInfractor = new javax.swing.JTextField();
        jComboBox_tipoID = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel_fechaCurso = new javax.swing.JLabel();
        jLabel_horaCursoInicio = new javax.swing.JLabel();
        jSpinner_horaInicioCurso = new javax.swing.JSpinner(new SpinnerDateModel());
        jLabel_horaFinalInicio = new javax.swing.JLabel();
        jTextField_idInstructor = new javax.swing.JTextField();
        jLabel_idInstructor = new javax.swing.JLabel();
        jDateChooser_fechaCurso = new com.toedter.calendar.JDateChooser();
        jSpinner_horaFinCurso = new javax.swing.JSpinner(new SpinnerDateModel());
        jButton_aceptar = new javax.swing.JButton();
        jButton_limpiar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel_fechaCurso1 = new javax.swing.JLabel();
        jTextField_numCertificado = new javax.swing.JTextField();
        jLabel_numCertificado = new javax.swing.JLabel();
        jDateChooser_fechaComparendo = new com.toedter.calendar.JDateChooser();
        jTextField_numComparendo = new javax.swing.JTextField();
        jLabel_numComparendo = new javax.swing.JLabel();
        jLabel_numResolucion = new javax.swing.JLabel();
        jTextField_numResolucion = new javax.swing.JTextField();
        jTextField_numOrganismo = new javax.swing.JTextField();
        jLabel_numOrganismo = new javax.swing.JLabel();
        jTextField_numReferenciaDesc = new javax.swing.JTextField();
        jLabel_numReferenciaDesc = new javax.swing.JLabel();
        jComboBox_tipoComparendo = new javax.swing.JComboBox();
        jLabel_tipoComparendo = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setTitle("Formulario de registro de cursos CIA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_fecha.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_fecha.setText("Fecha:");

        jLabel_hora.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_hora.setText("Hora:");

        jLabel_hora_mostrar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_hora_mostrar.setText("?");

        jLabel_fecha_mostrar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_fecha_mostrar.setText("?");

        jTextField_idFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_idFuncionarioKeyTyped(evt);
            }
        });

        jLabel_idFuncionario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_idFuncionario.setText("Identificación funcionario CIA:");
        jLabel_idFuncionario.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del infractor"));
        jPanel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jPanel3.setName(""); // NOI18N

        jLabel_idTipo1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_idTipo1.setText("Tipo de identificación:");
        jLabel_idTipo1.setToolTipText("");

        jLabel_idInfractor1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_idInfractor1.setText("Identificación del infractor:");
        jLabel_idInfractor1.setToolTipText("");

        jTextField_idInfractor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_idInfractorKeyTyped(evt);
            }
        });

        jComboBox_tipoID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cédula", "Tarjeta identidad", "Cédula Extranjería ", "Nit", "Pasaporte", "Carnet Diplomático", "Registro Civil", "Cédula venezolana" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_idInfractor1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_idInfractor, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_idTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_tipoID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_idTipo1)
                    .addComponent(jComboBox_tipoID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_idInfractor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_idInfractor1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del curso"));
        jPanel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jPanel2.setName(""); // NOI18N

        jLabel_fechaCurso.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_fechaCurso.setText("Fecha de realización del curso:");
        jLabel_fechaCurso.setToolTipText("");

        jLabel_horaCursoInicio.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_horaCursoInicio.setText("Hora de inicio del curso:");
        jLabel_horaCursoInicio.setToolTipText("");

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinner_horaInicioCurso, "HH:mm");
        jSpinner_horaInicioCurso.setEditor(de);

        jLabel_horaFinalInicio.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_horaFinalInicio.setText("Hora de finalización del curso:");
        jLabel_horaFinalInicio.setToolTipText("");

        jTextField_idInstructor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_idInstructorKeyTyped(evt);
            }
        });

        jLabel_idInstructor.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_idInstructor.setText("Identificación del instructor:");
        jLabel_idInstructor.setToolTipText("");

        JSpinner.DateEditor de2 = new JSpinner.DateEditor(jSpinner_horaFinCurso, "HH:mm");
        jSpinner_horaFinCurso.setEditor(de2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_fechaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser_fechaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel_horaCursoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSpinner_horaInicioCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel_idInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField_idInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel_horaFinalInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinner_horaFinCurso))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_fechaCurso)
                    .addComponent(jDateChooser_fechaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_horaCursoInicio)
                    .addComponent(jSpinner_horaInicioCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_horaFinalInicio)
                    .addComponent(jSpinner_horaFinCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_idInstructor)
                    .addComponent(jTextField_idInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jButton_aceptar.setBackground(new java.awt.Color(102, 102, 255));
        jButton_aceptar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_aceptar.setText("Aceptar");
        jButton_aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarActionPerformed(evt);
            }
        });

        jButton_limpiar.setBackground(new java.awt.Color(102, 102, 255));
        jButton_limpiar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_limpiar.setText("Limpiar");
        jButton_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });

        jButton_cancelar.setBackground(new java.awt.Color(102, 102, 255));
        jButton_cancelar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cancelar.setText("Cancelar");
        jButton_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del comparendo"));
        jPanel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jPanel4.setName(""); // NOI18N

        jLabel_fechaCurso1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_fechaCurso1.setText("Fecha del comparendo:");
        jLabel_fechaCurso1.setToolTipText("");

        jTextField_numCertificado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_numCertificadoKeyTyped(evt);
            }
        });

        jLabel_numCertificado.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_numCertificado.setText("Número de certificado:");
        jLabel_numCertificado.setToolTipText("");

        jTextField_numComparendo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_numComparendoKeyTyped(evt);
            }
        });

        jLabel_numComparendo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_numComparendo.setText("Número de comparendo:");
        jLabel_numComparendo.setToolTipText("");

        jLabel_numResolucion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_numResolucion.setText("Número de resolución:");
        jLabel_numResolucion.setToolTipText("");

        jTextField_numResolucion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_numResolucionKeyTyped(evt);
            }
        });

        jTextField_numOrganismo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_numOrganismoFocusLost(evt);
            }
        });
        jTextField_numOrganismo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_numOrganismoKeyTyped(evt);
            }
        });

        jLabel_numOrganismo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_numOrganismo.setText("Organismo de transito:");
        jLabel_numOrganismo.setToolTipText("");

        jLabel_numReferenciaDesc.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_numReferenciaDesc.setText("Número referencia de desc.");
        jLabel_numReferenciaDesc.setToolTipText("");

        jComboBox_tipoComparendo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PONAL", "POLCA" }));

        jLabel_tipoComparendo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_tipoComparendo.setText("Tipo de comparendo:");
        jLabel_tipoComparendo.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_fechaCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser_fechaComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel_numCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_numCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel_numComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_numComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel_numResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_numResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel_numOrganismo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_numOrganismo, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel_numReferenciaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_numReferenciaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_tipoComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_tipoComparendo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_fechaCurso1)
                    .addComponent(jDateChooser_fechaComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_numCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_numCertificado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_numComparendo)
                    .addComponent(jTextField_numComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_numResolucion)
                    .addComponent(jTextField_numResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_numOrganismo)
                    .addComponent(jTextField_numOrganismo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_numReferenciaDesc)
                    .addComponent(jTextField_numReferenciaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tipoComparendo)
                    .addComponent(jComboBox_tipoComparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel_fecha_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel_hora_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel_idFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_idFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_fecha)
                    .addComponent(jLabel_fecha_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_hora)
                    .addComponent(jLabel_hora_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_idFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_idFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_aceptar)
                    .addComponent(jButton_cancelar)
                    .addComponent(jButton_limpiar))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(603, 723));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarActionPerformed
        // TODO add your handling code here:
        
        FechaHora fecha = new FechaHora();
        
        //   INICIO conexion al WS
        
        ObjectFactory instancia = new ObjectFactory(); // Instancia para crear objetos en general
        
        DatosEntradaCursoCia cursoCIA =  instancia.createDatosEntradaCursoCia(); // Instancia de la entrada de los Datos del curso CIA
        
        cursoCIA.setCiudadCia("11001000"); // Fijo
        cursoCIA.setCodigoCia("9002852265"); // Fijo
        cursoCIA.setCodigoCurso("1"); // Fijo
        cursoCIA.setCodigoSedeCia("76834000"); // Fijo
        cursoCIA.setCodigoTransaccion("000003"); // Fijo
        cursoCIA.setDireccionAdquiriente("127.0.0.1");
        cursoCIA.setFechaRealizacionCurso("20150914");
        cursoCIA.setFechaTransaccion(fecha.fechaActual());
        cursoCIA.setFuncionarioRegistra("78456159");
        cursoCIA.setHoraFinCurso("1500");
        cursoCIA.setHoraInicioCurso("1300");
        cursoCIA.setHoraTransaccion(fecha.horaActual());
        cursoCIA.setIdentificacionInfractor("11348162");
        cursoCIA.setIdentificacionInstructor("66879056");
        cursoCIA.setNumeroSecuencia("10");
        cursoCIA.setTipoIdentificacion("1");
        
        CursoComparendo comparendosCursoCIA =  instancia.createCursoComparendo(); // Instancia de la entrada de los comparendos del Curso CIA
        
        comparendosCursoCIA.setFechaComparendo("20150914");
        comparendosCursoCIA.setNumeroCertificado("1478");
        comparendosCursoCIA.setNumeroComparendo("999999911445256");
        comparendosCursoCIA.setNumeroResolucion("1548");
        comparendosCursoCIA.setOrganismoTransito("25899000");
        comparendosCursoCIA.setReferenciaDescuento("150911001478" + luhnCheck("150911001478"));
        comparendosCursoCIA.setTipoComparendo("PONAL");
        
        cursoCIA.getComparendos().add(comparendosCursoCIA); // Agregar los comparendos al ArrayList
        
         
        System.out.println (luhnCheck("7992739871"));
        //System.out.println (cursoCIA.getComparendos().get(0));
        
        /*System.out.println ("Cod respuesta:  "+wsSimitCursoCia(cursoCIA).getCodigoRespuesta());
        System.out.println ("Fecha transaccion:  "+wsSimitCursoCia(cursoCIA).getFechaTransaccion());
        System.out.println ("Hora transaccion:  "+wsSimitCursoCia(cursoCIA).getHoraTransaccion());
        System.out.println ("Num Autorizacion:  "+wsSimitCursoCia(cursoCIA).getNumAutorizacion());
        System.out.println ("Mensaje respuesta del WS:  "+wsSimitCursoCia(cursoCIA).getMensajeRespuesta()); // METODO QUE ENVIA LA INFORMACION AL WS!!!!!!!!!!!!!!!!!!!!
        System.out.println ("Num secuencia:  "+wsSimitCursoCia(cursoCIA).getNumeroSecuencia());*/
        
        //   FIN conexion al WS
        
        
        //   INICIO Codigo del formulario
        
        /*try 
        {           
        datos=new String [13];
        datos[0]=(jTextField_codCurso.getText());
        datos[1]=(jTextField_dirIP.getText());
        datos[2]=(jTextField_codigoCIA.getText());
        datos[3]=(jTextField_ciudadCIA.getText());
        datos[4]=(jTextField_codigoSedeCIA.getText());
        datos[5]=(jSpinner_horaInicioCurso.getValue().toString());
        datos[6]=(jSpinner_horaFinalCurso.getValue().toString());
        datos[7]=("000003"); // Codigo de transaccion
        datos[8]=(jDateChooser_fechaCurso.getDate().toString());
        datos[9]=(jTextField_idFuncionario.getText());
        datos[10]=(jTextField_idInfractor.getText());
        datos[11]=(jTextField_idInstructor.getText());
        datos[12]=("192.0.0.1");

        if (datos[0].equals("") || datos[1].equals("") || datos[2].equals("") || datos[3].equals("") || datos[4].equals("") || datos[5].equals("") || datos[6].equals("") 
                || datos[7].equals("") || datos[8].equals("") || datos[9].equals("") || datos[10].equals("") || datos[11].equals("") || datos[12].equals(""))
        {
            JOptionPane.showMessageDialog(null,"Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            System.out.println ("Cod Curso "+datos[0]);
            System.out.println ("IP "+datos[1]);
            System.out.println ("Cod CIA "+datos[2]);
            System.out.println ("Cod Ciudad "+datos[3]);
            System.out.println ("Cod Sede CIA "+datos[4]);
            System.out.println ("Hora Inicio "+datos[5]);
            System.out.println ("Hora Final "+datos[6]);
            System.out.println ("Cod Transaccion "+datos[7]);
            System.out.println ("Fecha Curso "+datos[8]);
            System.out.println ("ID funcionario "+datos[9]);
            System.out.println ("ID infractor "+datos[10]);
            System.out.println ("ID instructor "+datos[11]);
            System.out.println ("Cod Curso "+datos[12]);
            /*
            Long.parseLong(jTextField_dni.getText());
            Long.parseLong(jTextField_telefono.getText());
            
            Agente registrar = new Agente(datos);
            
            try 
            {
                if (registrar.registrarAgente()==true)
                {
                    JOptionPane.showMessageDialog(null,"¡El registro ha sido realizado satisfactoriamente!", "Registrado", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }

            }       
            catch (        InstantiationException | IllegalAccessException | SQLException ex) 
            {
                //System.out.println("entro a existe hhhhhhhh");
                Logger.getLogger(Dialog_formularioAgente.class.getName()).log(Level.SEVERE, null, ex);
            }
           
                
        }
                  
        }

        catch (NumberFormatException s)
        {
            JOptionPane.showMessageDialog(null,"Los campos DNI y Telefono deben ser numeros y no debe\ncontener espacios ni puntos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        */
        //   FIN Codigo del formulario
    }//GEN-LAST:event_jButton_aceptarActionPerformed

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed
        // TODO add your handling code here:
        limpiarRegistros();
    }//GEN-LAST:event_jButton_limpiarActionPerformed

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_cancelarActionPerformed

    private void jTextField_idFuncionarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idFuncionarioKeyTyped
        // TODO add your handling code here:
        validarCamposNumericos(jTextField_idFuncionario,evt,16);
    }//GEN-LAST:event_jTextField_idFuncionarioKeyTyped

    private void jTextField_idInfractorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idInfractorKeyTyped
        // TODO add your handling code here:
        validarCamposNumericos(jTextField_idInfractor,evt,16);
    }//GEN-LAST:event_jTextField_idInfractorKeyTyped

    private void jTextField_idInstructorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idInstructorKeyTyped
        // TODO add your handling code here:
        validarCamposNumericos(jTextField_idInstructor,evt,16);
    }//GEN-LAST:event_jTextField_idInstructorKeyTyped

    private void jTextField_numCertificadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_numCertificadoKeyTyped
        // TODO add your handling code here:
        validarCamposNumericos(jTextField_numCertificado,evt,16);
    }//GEN-LAST:event_jTextField_numCertificadoKeyTyped

    private void jTextField_numComparendoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_numComparendoKeyTyped
        // TODO add your handling code here:
        validarCamposNumericos(jTextField_numComparendo,evt,20);
    }//GEN-LAST:event_jTextField_numComparendoKeyTyped

    private void jTextField_numResolucionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_numResolucionKeyTyped
        // TODO add your handling code here:
        validarCamposNumericos(jTextField_numResolucion,evt,20);
    }//GEN-LAST:event_jTextField_numResolucionKeyTyped

    private void jTextField_numOrganismoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_numOrganismoKeyTyped
        // TODO add your handling code here:
        validarCamposNumericos(jTextField_numOrganismo,evt,8);
    }//GEN-LAST:event_jTextField_numOrganismoKeyTyped

    private void jTextField_numOrganismoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_numOrganismoFocusLost
        // TODO add your handling code here:
        completarCampo(jTextField_numOrganismo,evt,8);
    }//GEN-LAST:event_jTextField_numOrganismoFocusLost
        
    public void limpiarRegistros()
    {
        
    }
   
    void asignarDatos(String[] datos) 
    {
        
    }
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_aceptar;
    public javax.swing.JButton jButton_cancelar;
    public javax.swing.JButton jButton_limpiar;
    private javax.swing.JComboBox jComboBox_tipoComparendo;
    private javax.swing.JComboBox jComboBox_tipoID;
    private com.toedter.calendar.JDateChooser jDateChooser_fechaComparendo;
    private com.toedter.calendar.JDateChooser jDateChooser_fechaCurso;
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JLabel jLabel_fechaCurso;
    private javax.swing.JLabel jLabel_fechaCurso1;
    private javax.swing.JLabel jLabel_fecha_mostrar;
    private javax.swing.JLabel jLabel_hora;
    private javax.swing.JLabel jLabel_horaCursoInicio;
    private javax.swing.JLabel jLabel_horaFinalInicio;
    private javax.swing.JLabel jLabel_hora_mostrar;
    private javax.swing.JLabel jLabel_idFuncionario;
    private javax.swing.JLabel jLabel_idInfractor1;
    private javax.swing.JLabel jLabel_idInstructor;
    private javax.swing.JLabel jLabel_idTipo1;
    private javax.swing.JLabel jLabel_numCertificado;
    private javax.swing.JLabel jLabel_numComparendo;
    private javax.swing.JLabel jLabel_numOrganismo;
    private javax.swing.JLabel jLabel_numReferenciaDesc;
    private javax.swing.JLabel jLabel_numResolucion;
    private javax.swing.JLabel jLabel_tipoComparendo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner jSpinner_horaFinCurso;
    private javax.swing.JSpinner jSpinner_horaInicioCurso;
    private javax.swing.JTextField jTextField_idFuncionario;
    private javax.swing.JTextField jTextField_idInfractor;
    private javax.swing.JTextField jTextField_idInstructor;
    private javax.swing.JTextField jTextField_numCertificado;
    private javax.swing.JTextField jTextField_numComparendo;
    private javax.swing.JTextField jTextField_numOrganismo;
    private javax.swing.JTextField jTextField_numReferenciaDesc;
    private javax.swing.JTextField jTextField_numResolucion;
    // End of variables declaration//GEN-END:variables

    private static DatosSalidaCursoCia wsSimitCursoCia(clientews.DatosEntradaCursoCia oe) 
    {
        clientews.WSSimitCursoService service = new clientews.WSSimitCursoService();
        clientews.WSSimitCurso port = service.getWSSimitCursoPort();
        return port.wsSimitCursoCia(oe);
    }
    
    public static int luhnCheck(String number) 
    {
        int s1 = 0, s2 = 0;
        number += "0";
        String reverse = new StringBuffer(number).reverse().toString();

        for (int i = 0 ;i < reverse.length();i++) 
        {
            int digit = Character.digit(reverse.charAt(i), 10);

            if(i % 2 == 0) 
            { 
                s1 += digit;
            }
            else 
            {
                s2 += 2 * digit;

                if (digit >= 5) 
                { 
                    s2 -= 9; 
                }
            }
        }
  
        return ((s1 + s2) * 9) % 10;
        
    }
    
    public void validarCamposNumericos(JTextField txt,KeyEvent evt,int pValor)
    {
        if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()))
        {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
           
        }
        
        if (txt.getText().length()>=pValor)
        {
            //JOptionPane.showMessageDialog(null,"Limite de caracteres"+pValor);
            //jLabelIdFuncionario.setText("Limite de caracteres"+pValor);
            evt.consume();
        }
        
    }
    public void completarCampo(JTextField txt,FocusEvent evt,int pValor)
    {
        String digito=null;
        if (txt.getText().length()>=1 && txt.getText().length()<= pValor ) {
            int result=txt.getText().length();
            int result2= pValor-result;
            for (int i = 1; i <= result2; i++) {
                digito = txt.getText()+"0";
                txt.setText(digito);
            }
        }
        
    }
    
}
