package clientews;


import clases.FechaHora;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JuanJo
 */
public class Dialog_formularioCursoCIA extends java.awt.Dialog {
String datos[];
    /**
     * Creates new form Dialog_formularioAgente
     */
    
    public JFrame_Principal menu;
    
    public Dialog_formularioCursoCIA(JFrame_Principal parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jButton_aceptar.setVisible(true);
        
        FechaHora fecha = new FechaHora();
        fecha.fecha(jLabel_fecha_mostrar);
        fecha.hora(jLabel_hora_mostrar);
        this.menu=parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_direccionIP = new javax.swing.JLabel();
        jLabel_codigoCIA = new javax.swing.JLabel();
        jLabel_ciudadCIA = new javax.swing.JLabel();
        jLabel_codigoSedeCIA = new javax.swing.JLabel();
        jTextField_dirIP = new javax.swing.JTextField();
        jTextField_codigoCIA = new javax.swing.JTextField();
        jTextField_ciudadCIA = new javax.swing.JTextField();
        jTextField_codigoSedeCIA = new javax.swing.JTextField();
        jButton_aceptar = new javax.swing.JButton();
        jButton_limpiar = new javax.swing.JButton();
        jLabel_fecha = new javax.swing.JLabel();
        jButton_cancelar = new javax.swing.JButton();
        jLabel_hora = new javax.swing.JLabel();
        jLabel_hora_mostrar = new javax.swing.JLabel();
        jLabel_fecha_mostrar = new javax.swing.JLabel();
        jTextField_idFuncionario = new javax.swing.JTextField();
        jLabel_idFuncionario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_fechaCurso = new javax.swing.JLabel();
        jLabel_codCurso = new javax.swing.JLabel();
        jTextField_codCurso = new javax.swing.JTextField();
        jLabel_horaCursoInicio = new javax.swing.JLabel();
        jSpinner_horaInicioCurso = new javax.swing.JSpinner(new SpinnerDateModel());
        jSpinner_horaFinalCurso = new javax.swing.JSpinner(new SpinnerDateModel());
        jLabel_horaFinalInicio = new javax.swing.JLabel();
        jTextField_idInstructor = new javax.swing.JTextField();
        jLabel_idInstructor = new javax.swing.JLabel();
        jDateChooser_fechaCurso = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel_idTipo1 = new javax.swing.JLabel();
        jLabel_idInfractor1 = new javax.swing.JLabel();
        jTextField_idInfractor = new javax.swing.JTextField();
        jComboBox_tipoID = new javax.swing.JComboBox();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setTitle("Formulario de registro de cursos CIA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jLabel_direccionIP.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_direccionIP.setText("Dirección IP:");
        add(jLabel_direccionIP);
        jLabel_direccionIP.setBounds(20, 550, 90, 18);

        jLabel_codigoCIA.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_codigoCIA.setText("Código CIA:");
        add(jLabel_codigoCIA);
        jLabel_codigoCIA.setBounds(20, 80, 80, 18);

        jLabel_ciudadCIA.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_ciudadCIA.setText("Ciudad CIA:");
        add(jLabel_ciudadCIA);
        jLabel_ciudadCIA.setBounds(20, 120, 90, 18);

        jLabel_codigoSedeCIA.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_codigoSedeCIA.setText("Código de la sede CIA:");
        add(jLabel_codigoSedeCIA);
        jLabel_codigoSedeCIA.setBounds(20, 160, 150, 18);
        add(jTextField_dirIP);
        jTextField_dirIP.setBounds(240, 550, 331, 27);
        add(jTextField_codigoCIA);
        jTextField_codigoCIA.setBounds(240, 80, 331, 27);
        add(jTextField_ciudadCIA);
        jTextField_ciudadCIA.setBounds(240, 120, 331, 27);
        add(jTextField_codigoSedeCIA);
        jTextField_codigoSedeCIA.setBounds(240, 160, 331, 27);

        jButton_aceptar.setBackground(new java.awt.Color(255, 204, 102));
        jButton_aceptar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_aceptar.setText("Aceptar");
        jButton_aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarActionPerformed(evt);
            }
        });
        add(jButton_aceptar);
        jButton_aceptar.setBounds(110, 680, 90, 27);

        jButton_limpiar.setBackground(new java.awt.Color(255, 204, 102));
        jButton_limpiar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_limpiar.setText("Limpiar");
        jButton_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });
        add(jButton_limpiar);
        jButton_limpiar.setBounds(390, 680, 95, 27);

        jLabel_fecha.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_fecha.setText("Fecha:");
        add(jLabel_fecha);
        jLabel_fecha.setBounds(430, 30, 50, 18);

        jButton_cancelar.setBackground(new java.awt.Color(255, 204, 102));
        jButton_cancelar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_cancelar.setText("Cancelar");
        jButton_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });
        add(jButton_cancelar);
        jButton_cancelar.setBounds(250, 680, 96, 27);

        jLabel_hora.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_hora.setText("Hora:");
        add(jLabel_hora);
        jLabel_hora.setBounds(430, 50, 50, 18);

        jLabel_hora_mostrar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_hora_mostrar.setText("?");
        add(jLabel_hora_mostrar);
        jLabel_hora_mostrar.setBounds(480, 50, 100, 20);

        jLabel_fecha_mostrar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_fecha_mostrar.setText("?");
        add(jLabel_fecha_mostrar);
        jLabel_fecha_mostrar.setBounds(480, 30, 100, 20);
        add(jTextField_idFuncionario);
        jTextField_idFuncionario.setBounds(240, 200, 331, 27);

        jLabel_idFuncionario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_idFuncionario.setText("Identificación funcionario CIA:");
        jLabel_idFuncionario.setToolTipText("");
        add(jLabel_idFuncionario);
        jLabel_idFuncionario.setBounds(20, 200, 210, 18);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del curso"));
        jPanel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jPanel2.setName(""); // NOI18N

        jLabel_fechaCurso.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_fechaCurso.setText("Fecha de realización del curso:");
        jLabel_fechaCurso.setToolTipText("");

        jLabel_codCurso.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_codCurso.setText("Código del curso:");
        jLabel_codCurso.setToolTipText("");

        jLabel_horaCursoInicio.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_horaCursoInicio.setText("Hora de inicio del curso:");
        jLabel_horaCursoInicio.setToolTipText("");

        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinner_horaInicioCurso, "HH:mm");
        jSpinner_horaInicioCurso.setEditor(de);

        Date date2 = new Date();
        SpinnerDateModel sm2 = new SpinnerDateModel(date2, null, null, Calendar.HOUR_OF_DAY);
        JSpinner.DateEditor de2 = new JSpinner.DateEditor(jSpinner_horaInicioCurso, "HH:mm");
        jSpinner_horaFinalCurso.setEditor(de2);

        jLabel_horaFinalInicio.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_horaFinalInicio.setText("Hora de finalización del curso:");
        jLabel_horaFinalInicio.setToolTipText("");

        jLabel_idInstructor.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_idInstructor.setText("Identificación del instructor:");
        jLabel_idInstructor.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_fechaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser_fechaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_codCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jTextField_codCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel_horaCursoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSpinner_horaInicioCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel_horaFinalInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSpinner_horaFinalCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel_idInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField_idInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_codCurso)
                    .addComponent(jTextField_codCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_fechaCurso)
                    .addComponent(jDateChooser_fechaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_horaCursoInicio)
                    .addComponent(jSpinner_horaInicioCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_horaFinalInicio)
                    .addComponent(jSpinner_horaFinalCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_idInstructor)
                    .addComponent(jTextField_idInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel2);
        jPanel2.setBounds(10, 330, 570, 210);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del infractor"));
        jPanel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jPanel3.setName(""); // NOI18N

        jLabel_idTipo1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_idTipo1.setText("Tipo de identificación:");
        jLabel_idTipo1.setToolTipText("");

        jLabel_idInfractor1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_idInfractor1.setText("Identificación del infractor:");
        jLabel_idInfractor1.setToolTipText("");

        jComboBox_tipoID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cédula", "Tarjeta identidad", "Cédula Extranjería ", "Nit", "Pasaporte", "Carnet Diplomático", "Registro Civil", "Cédula venezolana" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_idInfractor1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_idInfractor, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_idTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_tipoID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_idTipo1)
                    .addComponent(jComboBox_tipoID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_idInfractor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_idInfractor1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel3);
        jPanel3.setBounds(10, 230, 570, 100);

        setSize(new java.awt.Dimension(603, 751));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        JFrame_Principal user = new JFrame_Principal();
        user.setVisible(true);
        user.pack();
    }//GEN-LAST:event_closeDialog

    private void jButton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarActionPerformed
        // TODO add your handling code here:
        
        FechaHora fecha = new FechaHora();
        
        //   INICIO conexion al WS
        
        ObjectFactory instancia = new ObjectFactory(); // Instancia para crear objetos en general
        
        DatosEntradaCursoCia cursoCIA =  instancia.createDatosEntradaCursoCia(); // Instancia de la entrada de los Datos del curso CIA
        
        cursoCIA.setCiudadCia("11001000"); // Fijo
        cursoCIA.setCodigoCia("9002852265"); // Fijo
        cursoCIA.setCodigoCurso("1"); // Fijo
        cursoCIA.setCodigoSedeCia("76834000"); // Fijo
        cursoCIA.setCodigoTransaccion("000003"); // Fijo
        cursoCIA.setDireccionAdquiriente("127.0.0.1");
        cursoCIA.setFechaRealizacionCurso("20150914");
        cursoCIA.setFechaTransaccion(fecha.fechaActual());
        cursoCIA.setFuncionarioRegistra("78456159");
        cursoCIA.setHoraFinCurso("1500");
        cursoCIA.setHoraInicioCurso("1300");
        cursoCIA.setHoraTransaccion(fecha.horaActual());
        cursoCIA.setIdentificacionInfractor("11348162");
        cursoCIA.setIdentificacionInstructor("66879056");
        cursoCIA.setNumeroSecuencia("10");
        cursoCIA.setTipoIdentificacion("1");
        
        CursoComparendo comparendosCursoCIA =  instancia.createCursoComparendo(); // Instancia de la entrada de los comparendos del Curso CIA
        
        comparendosCursoCIA.setFechaComparendo("20150914");
        comparendosCursoCIA.setNumeroCertificado("1478");
        comparendosCursoCIA.setNumeroComparendo("999999911445256");
        comparendosCursoCIA.setNumeroResolucion("1548");
        comparendosCursoCIA.setOrganismoTransito("25899000");
        comparendosCursoCIA.setReferenciaDescuento("150911001478" + luhnCheck("150911001478"));
        comparendosCursoCIA.setTipoComparendo("PONAL");
        
        cursoCIA.getComparendos().add(comparendosCursoCIA); // Agregar los comparendos al ArrayList
        
         
        System.out.println (luhnCheck("7992739871"));
        //System.out.println (cursoCIA.getComparendos().get(0));
        
        /*System.out.println ("Cod respuesta:  "+wsSimitCursoCia(cursoCIA).getCodigoRespuesta());
        System.out.println ("Fecha transaccion:  "+wsSimitCursoCia(cursoCIA).getFechaTransaccion());
        System.out.println ("Hora transaccion:  "+wsSimitCursoCia(cursoCIA).getHoraTransaccion());
        System.out.println ("Num Autorizacion:  "+wsSimitCursoCia(cursoCIA).getNumAutorizacion());
        System.out.println ("Mensaje respuesta del WS:  "+wsSimitCursoCia(cursoCIA).getMensajeRespuesta()); // METODO QUE ENVIA LA INFORMACION AL WS!!!!!!!!!!!!!!!!!!!!
        System.out.println ("Num secuencia:  "+wsSimitCursoCia(cursoCIA).getNumeroSecuencia());*/
        
        //   FIN conexion al WS
        
        
        //   INICIO Codigo del formulario
        
        /*try 
        {           
        datos=new String [13];
        datos[0]=(jTextField_codCurso.getText());
        datos[1]=(jTextField_dirIP.getText());
        datos[2]=(jTextField_codigoCIA.getText());
        datos[3]=(jTextField_ciudadCIA.getText());
        datos[4]=(jTextField_codigoSedeCIA.getText());
        datos[5]=(jSpinner_horaInicioCurso.getValue().toString());
        datos[6]=(jSpinner_horaFinalCurso.getValue().toString());
        datos[7]=("000003"); // Codigo de transaccion
        datos[8]=(jDateChooser_fechaCurso.getDate().toString());
        datos[9]=(jTextField_idFuncionario.getText());
        datos[10]=(jTextField_idInfractor.getText());
        datos[11]=(jTextField_idInstructor.getText());
        datos[12]=("192.0.0.1");

        if (datos[0].equals("") || datos[1].equals("") || datos[2].equals("") || datos[3].equals("") || datos[4].equals("") || datos[5].equals("") || datos[6].equals("") 
                || datos[7].equals("") || datos[8].equals("") || datos[9].equals("") || datos[10].equals("") || datos[11].equals("") || datos[12].equals(""))
        {
            JOptionPane.showMessageDialog(null,"Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            System.out.println ("Cod Curso "+datos[0]);
            System.out.println ("IP "+datos[1]);
            System.out.println ("Cod CIA "+datos[2]);
            System.out.println ("Cod Ciudad "+datos[3]);
            System.out.println ("Cod Sede CIA "+datos[4]);
            System.out.println ("Hora Inicio "+datos[5]);
            System.out.println ("Hora Final "+datos[6]);
            System.out.println ("Cod Transaccion "+datos[7]);
            System.out.println ("Fecha Curso "+datos[8]);
            System.out.println ("ID funcionario "+datos[9]);
            System.out.println ("ID infractor "+datos[10]);
            System.out.println ("ID instructor "+datos[11]);
            System.out.println ("Cod Curso "+datos[12]);
            /*
            Long.parseLong(jTextField_dni.getText());
            Long.parseLong(jTextField_telefono.getText());
            
            Agente registrar = new Agente(datos);
            
            try 
            {
                if (registrar.registrarAgente()==true)
                {
                    JOptionPane.showMessageDialog(null,"¡El registro ha sido realizado satisfactoriamente!", "Registrado", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }

            }       
            catch (        InstantiationException | IllegalAccessException | SQLException ex) 
            {
                //System.out.println("entro a existe hhhhhhhh");
                Logger.getLogger(Dialog_formularioAgente.class.getName()).log(Level.SEVERE, null, ex);
            }
           
                
        }
                  
        }

        catch (NumberFormatException s)
        {
            JOptionPane.showMessageDialog(null,"Los campos DNI y Telefono deben ser numeros y no debe\ncontener espacios ni puntos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        */
        //   FIN Codigo del formulario
    }//GEN-LAST:event_jButton_aceptarActionPerformed

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed
        // TODO add your handling code here:
        limpiarRegistros();
    }//GEN-LAST:event_jButton_limpiarActionPerformed

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame_Principal user = new JFrame_Principal();
        user.setVisible(true);
        user.pack();
    }//GEN-LAST:event_jButton_cancelarActionPerformed
    
    public void limpiarRegistros()
    {
        jTextField_codCurso.setText("");
        jTextField_dirIP.setText("");
        jTextField_codigoCIA.setText("");
        jTextField_ciudadCIA.setText("");
        jTextField_codigoSedeCIA.setText("");
    }
    
    void asignarDatos(String[] datos) 
    {
        jTextField_codCurso.setText(datos[0]);
        jTextField_dirIP.setText(datos[1]);
        jTextField_codigoCIA.setText(datos[2]);
        jTextField_ciudadCIA.setText(datos[3]);
        jTextField_codigoSedeCIA.setText(datos[4]);
    }
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_aceptar;
    public javax.swing.JButton jButton_cancelar;
    public javax.swing.JButton jButton_limpiar;
    private javax.swing.JComboBox jComboBox_tipoID;
    private com.toedter.calendar.JDateChooser jDateChooser_fechaCurso;
    private javax.swing.JLabel jLabel_ciudadCIA;
    private javax.swing.JLabel jLabel_codCurso;
    private javax.swing.JLabel jLabel_codigoCIA;
    private javax.swing.JLabel jLabel_codigoSedeCIA;
    private javax.swing.JLabel jLabel_direccionIP;
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JLabel jLabel_fechaCurso;
    private javax.swing.JLabel jLabel_fecha_mostrar;
    private javax.swing.JLabel jLabel_hora;
    private javax.swing.JLabel jLabel_horaCursoInicio;
    private javax.swing.JLabel jLabel_horaFinalInicio;
    private javax.swing.JLabel jLabel_hora_mostrar;
    private javax.swing.JLabel jLabel_idFuncionario;
    private javax.swing.JLabel jLabel_idInfractor1;
    private javax.swing.JLabel jLabel_idInstructor;
    private javax.swing.JLabel jLabel_idTipo1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner_horaFinalCurso;
    private javax.swing.JSpinner jSpinner_horaInicioCurso;
    private javax.swing.JTextField jTextField_ciudadCIA;
    private javax.swing.JTextField jTextField_codCurso;
    private javax.swing.JTextField jTextField_codigoCIA;
    private javax.swing.JTextField jTextField_codigoSedeCIA;
    private javax.swing.JTextField jTextField_dirIP;
    private javax.swing.JTextField jTextField_idFuncionario;
    private javax.swing.JTextField jTextField_idInfractor;
    private javax.swing.JTextField jTextField_idInstructor;
    // End of variables declaration//GEN-END:variables

    private static DatosSalidaCursoCia wsSimitCursoCia(clientews.DatosEntradaCursoCia oe) 
    {
        clientews.WSSimitCursoService service = new clientews.WSSimitCursoService();
        clientews.WSSimitCurso port = service.getWSSimitCursoPort();
        return port.wsSimitCursoCia(oe);
    }
    
    public static int luhnCheck(String number) 
    {
        int s1 = 0, s2 = 0;
        number += "0";
        String reverse = new StringBuffer(number).reverse().toString();

        for (int i = 0 ;i < reverse.length();i++) 
        {
            int digit = Character.digit(reverse.charAt(i), 10);

            if(i % 2 == 0) 
            { 
                s1 += digit;
            }
            else 
            {
                s2 += 2 * digit;

                if (digit >= 5) 
                { 
                    s2 -= 9; 
                }
            }
        }
  
        return ((s1 + s2) * 9) % 10;
        
	}
    
}
